source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def frameworks_pods
    pod 'CellularModelDataSource', :path => '../'
end

target 'Example' do
  platform :ios, '12.0'
  frameworks_pods
end
