language: swift
osx_image: xcode10.1

# Dependencies
before_install: chmod +x ./.travis/deps.sh
install: ./.travis/deps.sh

# Build Script
before_script: chmod +x ./.travis/build.sh
script: ./.travis/build.sh

# Update Code Coverage
after_success: bash <(curl -s https://codecov.io/bash)

# Build Matrix
matrix:
    include:
        # iOS
        - env: DESTINATION="OS=12.1,name=iPhone XS Max"   SCHEME="ModelDataSource iOS" RUN_TESTS="YES" POD_LINT="NO"
        - env: DESTINATION="OS=11.3,name=iPhone X"        SCHEME="ModelDataSource iOS" RUN_TESTS="YES" POD_LINT="NO"
        - env: DESTINATION="OS=10.3.1,name=iPhone 7 Plus" SCHEME="ModelDataSource iOS" RUN_TESTS="YES" POD_LINT="NO"
        - env: DESTINATION="OS=9.3,name=iPhone 6"         SCHEME="ModelDataSource iOS" RUN_TESTS="YES" POD_LINT="NO"
        # tvOS
        - env: DESTINATION="OS=12.1,name=Apple TV 4K"    SCHEME="ModelDataSource tvOS" RUN_TESTS="YES" POD_LINT="NO"
        - env: DESTINATION="OS=11.3,name=Apple TV 4K"    SCHEME="ModelDataSource tvOS" RUN_TESTS="YES" POD_LINT="NO"
        - env: DESTINATION="OS=10.2,name=Apple TV 1080p" SCHEME="ModelDataSource tvOS" RUN_TESTS="YES" POD_LINT="NO"
        - env: DESTINATION="OS=9.2,name=Apple TV 1080p"  SCHEME="ModelDataSource tvOS" RUN_TESTS="YES" POD_LINT="NO"

